version: "3"

volumes:
  datastore-data:

services:
  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=brent-local
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    volumes:
       - datastore-data:/opt/data
    ports:
      - "8081:8081"
